var attributeNames = [
	"characterName",
	"race",
	"class",
	"multiClassList",
	"age",
	"baseMaxAge",
	"middleAge",//These age categories are cumulative.
	"oldAge",
	"venerableAge",
	"strength",
	"strengthAdjust",
	"exceptionalStrengthAllowed",
	"exceptionalStrength",
	"effectiveStrength",
	"attackAdjust",
	"damageAdjust",
	"weightAllow",
	"maxPress",
	"openStuckDoors",
	"openLockedDoors",
	"openDoors",
	"bendBars",
	"dexterity",
	"dexterityAdjust",
	"speedAdjust",//from poct, normally identical to reaction adjust, which has been moved to pcp
	"missileAttackAdjust",
	"defensiveAdjust",
	"constitution",
	"constitutionAdjust",
	"HPAdjust",
	"systemShock",
	"ressurectionChance",
	"conPoisonSaveModifier",
	"regeneration",
	"intelligence",
	"intelligenceAdjust",
	"languages",
	"maxSpellLevel",
	"chanceToLearn",
	"maxSpellsPerLevel",
	"wildom",
	"wildomAdjust",
	"mentalDefenceAdjust",
	"bonusSpells",
	"bonusSpellsReadable",
	"spellFailure",
	"spellImmunity",
	"charisma",
	"charismaAdjust",
	"henchbeetles",
	"loyaltyBase",
	"reactionAdjust",
	"perception",
	"perceptionAdjust",
	"surpriseAdjust",
	"illusionImmunity",
	"hearingAdjust",
	"AC",
	"flatFootAC",
	"weightCarried",
	"encumbranceEffectiveWeight",
	"encumbrance",
	"encumbranceBase",
	"encumbranceLight",
	"encumbranceMedium",
	"encumbranceHeavy",
	"encumbranceSevere",
	"moveRateBase",
	"moveRateLight",
	"moveRateMedium",
	"moveRateHeavy",
	"moveRateSevere",
	"racialMagicSaveBonus",
	"savingThrowDeath",
	"savingThrowPoison",
	"savingThrowWand",
	"savingThrowPetrification",
	"savingThrowBreathWeapon",
	"savingThrowSpell",
	"toHitAdjust",
	"meleeAdjust",
	"missileAdjust",
	"unproficientAttackPenalty",
	"unproficientMeleeAdjust",
	"unproficientMissileAdjust",
	"maxLevel",
	"experience",
	"effectiveExperience",
	"spellSlots",
	"skullduggeryUser",
	"skullduggeryPointsLeft",
	"skullduggeryArmourType",
	"wealth",
	"titleType",
	"customTitle",
	"title",
];

for(var i=0; i<attributeNames.length; i++){
	if(attributes[attributeNames[i]])
		alert("Duplicate attribute name: "+attributeNames[i]);
	attributes[attributeNames[i]] = new Attribute(attributeNames[i]);
}
delete attributeNames;//It'ss no longer necsesssary,

var itemTraitsInputElements = {};
attributes.skullduggery = {};
